displayName=Aggro Tag
author=SvO2
support=https://github.com/Bellefeu/aggro-tag
description=Shows a red name above NPCs that will attack you on sight, with aggro radius and Line of Sight.
tags=aggro,aggressive,npc,combat,overlay,highlight,danger,max hit,slayer,bossing,gwd,targeting,minigame,disguise,collision,line of sight,true tile,tolerance,hardcore,ironman,tag,marker,mark,bosses,boss,enemies,enemy,pvm,PvM
plugins=com.aggrotag.AggroTagPlugin
build=standard